import streamlit as st
import json
import os
import glob
import time

# 1. Page Configuration
st.set_page_config(page_title="MalGAN Blue Team SOC", layout="wide", page_icon="🛡️")
st.title("🛡️ Threat Intelligence Dashboard")
st.markdown("Monitoring live evasion attempts from the Adversarial GAN.")

# 2. Securely get the data directory from our vault
data_dir = os.getenv("DATA_DIRECTORY", "./data")

# 3. Function to read the alerts generated by your Orchestrator
def fetch_alerts():
    alerts = []
    if os.path.exists(data_dir):
        # Find all JSON files in the data folder
        search_pattern = os.path.join(data_dir, "*.json")
        for filepath in glob.glob(search_pattern):
            try:
                with open(filepath, 'r') as f:
                    alerts.append(json.load(f))
            except json.JSONDecodeError:
                pass
    return alerts

# 4. Fetch the data
alerts = fetch_alerts()

# 5. Build the UI
col1, col2, col3 = st.columns(3)
col1.metric("System Status", "ONLINE", delta="Protected", delta_color="normal")
col2.metric("Total Scans", "Continuous")
col3.metric("Evasion Attempts", len(alerts), delta="-Critical" if len(alerts) > 0 else "0", delta_color="inverse")

st.divider()

# 6. Display the Threat Intel
if not alerts:
    st.success("✅ System Secure. No evasive malware detected in the perimeter.")
else:
    st.error(f"🚨 WARNING: {len(alerts)} Evasive Threat(s) Detected!")
    
    for alert in alerts:
        # Create a dropdown box for each alert
        sample_id = alert.get("sample_id", "Unknown")
        with st.expander(f"☠️ Threat Report: {sample_id}", expanded=True):
            st.warning(alert.get("threat_intel", "No details provided."))
            
            # Show the raw JSON data nicely formatted
            st.json(alert)

# 7. Auto-Refresh Button
if st.button("🔄 Refresh Radar"):
    st.rerun()